version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lesson-view-postgres
    restart: always
    environment:
      POSTGRES_USER: lesson
      POSTGRES_PASSWORD: lesson
      POSTGRES_DB: lesson_view
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: lesson_view_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  pgdata:
